application: xtern-matching-143216
version: 1
runtime: go
api_version: go1

handlers:

# Serving static files
- url: /public
  static_dir: public

- url: /node_modules
  static_dir: node_modules

- url: .*
  script: _go_app