application:xtern-matching
version: 1
runtime: go
api_version: go1

handlers:

# Serving static files
- url: /public
  static_dir: public

- url: /index\.html
  script: _go_app

- url: /.*
  script: _go_app