version: 3
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /
  static_files: index\.html
  upload: index.html

- url: /favicon\.ico
  static_files: favicon\ico
  upload: favicon.ico

# Serving static files
- url: /public
  static_dir: public

- url: /semantic
  static_dir: semantic

- url: /node_modules
  static_dir: node_modules

- url: .*
  script: _go_app

env_variables:
  XTERN_ENVIRONMENT: 'production'
  GOOGLE_APPLICATION_CREDENTIALS: 'environments/production/cloudstore.json'
