runtime: go
api_version: go1
threadsafe: true

inbound_services:
- warmup

handlers:
- url: /
  static_files: index.html
  upload: index.html

# Serving static files
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /public
  static_dir: public
- url: /semantic
  static_dir: semantic
- url: /node_modules
  static_dir: node_modules

- url: /environments
  static_dir: environments

- url: /_ah/warmup
  script: _go_app
  login: admin

- url: /_ah/start
  script: _go_app
  login: admin

- url: .*
  script: _go_app

env_variables:
  XTERN_ENVIRONMENT: 'development'
