runtime: go
api_version: go1
threadsafe: true]
application: xtern-matching-173700
version: 1

inbound_services:
- warmup

handlers:
- url: /
  static_files: index.html
  upload: index.html

# Serving static files
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /public
  static_dir: public
- url: /semantic
  static_dir: semantic
- url: /output.min.js
  static_files: output.min.js
  upload: output.min.js
- url: /bundle.js
  static_files: bundle.js
  upload: bundle.js
- url: /output.min.css
  static_files: output.min.css
  upload: output.min.css


- url: /environments
  static_dir: environments

- url: /_ah/warmup
  script: _go_app
  login: admin

- url: /_ah/start
  script: _go_app
  login: admin

- url: .*
  script: _go_app

env_variables:
  XTERN_ENVIRONMENT: 'development'
