version: 1
application: xtern-matching-143216
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

# Serving static files
- url: /public
  static_dir: public

- url: /semantic
  static_dir: semantic

- url: /node_modules
  static_dir: node_modules

- url: .*
  script: _go_app

#skip_files: